name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1

    - name: Build and push Docker image
      run: |
        docker build -t student_management_backend .
        docker tag student_management_backend:latest 637423452251.dkr.ecr.us-east-1.amazonaws.com/student_management_backend:latest
        docker push 637423452251.dkr.ecr.us-east-1.amazonaws.com/student_management_backend:latest
